apiVersion: v1
kind: ServiceAccount
metadata:
  name: dagster
  labels:
    helm.sh/chart: dagster-0.1.0
    app.kubernetes.io/name: dagster
    app.kubernetes.io/instance: dagster
    app.kubernetes.io/version: "0.6.9"
    app.kubernetes.io/managed-by: Tiller
