apiVersion: v1
kind: Service
metadata:
  name: dagster-database
  namespace: data
  labels:
    app: dagster-database
    release: daster
    heritage: Tiller
spec:
  type: 'ClusterIP'
  ports:
    - port: 5432
      name: ingress
      targetPort: ingress
      protocol: TCP
  selector:
    app: dagster-database
    release: dagster
